title: "Mis reflexiones"
theme: minima        # Tema por defecto de Jekyll (sencillo)
baseurl: "/alberto.arrula"  # ¡El nombre de tu repositorio!
url: "https://cr4t0s.github.io"
permalink: /:categories/:year/:month/:day/:title.html